/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jkvasir_engine_rendering_Material */

#ifndef _Included_jkvasir_engine_rendering_Material
#define _Included_jkvasir_engine_rendering_Material
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jkvasir_engine_rendering_Material
 * Method:    nativeNew
 * Signature: (Ljkvasir/engine/rendering/RenderBase;)J
 */
JNIEXPORT jlong JNICALL Java_jkvasir_engine_rendering_Material_nativeNew
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jkvasir_engine_rendering_Material
 * Method:    bind
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_Material_bind
  (JNIEnv *, jobject);

/*
 * Class:     jkvasir_engine_rendering_Material
 * Method:    getNumTextures
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jkvasir_engine_rendering_Material_getNumTextures
  (JNIEnv *, jobject);

/*
 * Class:     jkvasir_engine_rendering_Material
 * Method:    setTexture
 * Signature: (JLjkvasir/engine/rendering/Texture;)V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_Material_setTexture
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     jkvasir_engine_rendering_Material
 * Method:    getTexture
 * Signature: (J)Ljkvasir/engine/rendering/Texture;
 */
JNIEXPORT jobject JNICALL Java_jkvasir_engine_rendering_Material_getTexture
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
