/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jkvasir_engine_rendering_Shader */

#ifndef _Included_jkvasir_engine_rendering_Shader
#define _Included_jkvasir_engine_rendering_Shader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jkvasir_engine_rendering_Shader
 * Method:    nativeNew
 * Signature: (Ljkvasir/engine/rendering/RenderBase;)J
 */
JNIEXPORT jlong JNICALL Java_jkvasir_engine_rendering_Shader_nativeNew
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
