/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jkvasir_engine_rendering_Buffer */

#ifndef _Included_jkvasir_engine_rendering_Buffer
#define _Included_jkvasir_engine_rendering_Buffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jkvasir_engine_rendering_Buffer
 * Method:    nativeNew
 * Signature: (Ljkvasir/engine/rendering/RenderBase;)J
 */
JNIEXPORT jlong JNICALL Java_jkvasir_engine_rendering_Buffer_nativeNew
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jkvasir_engine_rendering_Buffer
 * Method:    genBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_Buffer_genBuffer
  (JNIEnv *, jobject);

/*
 * Class:     jkvasir_engine_rendering_Buffer
 * Method:    setData
 * Signature: ([BJZ)V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_Buffer_setData
  (JNIEnv *, jobject, jbyteArray, jlong, jboolean);

/*
 * Class:     jkvasir_engine_rendering_Buffer
 * Method:    subData
 * Signature: ([BJJ)V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_Buffer_subData
  (JNIEnv *, jobject, jbyteArray, jlong, jlong);

/*
 * Class:     jkvasir_engine_rendering_Buffer
 * Method:    getData
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jkvasir_engine_rendering_Buffer_getData
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     jkvasir_engine_rendering_Buffer
 * Method:    attribPtr
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_Buffer_attribPtr
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     jkvasir_engine_rendering_Buffer
 * Method:    bindBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_Buffer_bindBuffer
  (JNIEnv *, jobject);

/*
 * Class:     jkvasir_engine_rendering_Buffer
 * Method:    bindVAO
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_Buffer_bindVAO
  (JNIEnv *, jobject);

/*
 * Class:     jkvasir_engine_rendering_Buffer
 * Method:    freeBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_Buffer_freeBuffer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
