/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jkvasir_KvasirEngine */

#ifndef _Included_jkvasir_KvasirEngine
#define _Included_jkvasir_KvasirEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jkvasir_KvasirEngine
 * Method:    kvasirInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jkvasir_KvasirEngine_kvasirInit
  (JNIEnv *, jclass);

/*
 * Class:     jkvasir_KvasirEngine
 * Method:    kvasirDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jkvasir_KvasirEngine_kvasirDestroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
