/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jkvasir_engine_rendering_TextureImage */

#ifndef _Included_jkvasir_engine_rendering_TextureImage
#define _Included_jkvasir_engine_rendering_TextureImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jkvasir_engine_rendering_TextureImage
 * Method:    nativeNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jkvasir_engine_rendering_TextureImage_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     jkvasir_engine_rendering_TextureImage
 * Method:    getWidth
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jkvasir_engine_rendering_TextureImage_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     jkvasir_engine_rendering_TextureImage
 * Method:    getHeight
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jkvasir_engine_rendering_TextureImage_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     jkvasir_engine_rendering_TextureImage
 * Method:    getPixels
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_jkvasir_engine_rendering_TextureImage_getPixels
  (JNIEnv *, jobject);

/*
 * Class:     jkvasir_engine_rendering_TextureImage
 * Method:    setPixels
 * Signature: ([JJJ)V
 */
JNIEXPORT void JNICALL Java_jkvasir_engine_rendering_TextureImage_setPixels
  (JNIEnv *, jobject, jlongArray, jlong, jlong);

/*
 * Class:     jkvasir_engine_rendering_TextureImage
 * Method:    pixelRGB
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_jkvasir_engine_rendering_TextureImage_pixelRGB
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
